apiVersion: apps/v2
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice
        image: sumyatphyoe/cartservice:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v2
kind: Service
metadata:
  name: cartservice
spec:
  type: NodePort
  selector:
    app: cartservice
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32252